CREATE TABLE IF NOT EXISTS `checkout_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reservation_id` BIGINT UNSIGNED NOT NULL,
  `property_id` BIGINT UNSIGNED NOT NULL,
  `checkout_type` ENUM('scheduled', 'early') NOT NULL DEFAULT 'scheduled',
  `scheduled_check_out_date` DATE NOT NULL,
  `actual_check_out_date` DATE NOT NULL,
  `scheduled_nights` INT UNSIGNED NOT NULL,
  `actual_nights` INT UNSIGNED NOT NULL,
  `unused_nights` INT UNSIGNED NOT NULL DEFAULT 0,
  `rate_per_night` DECIMAL(12, 2) NOT NULL,
  `scheduled_room_total` DECIMAL(12, 2) NOT NULL,
  `actual_room_total` DECIMAL(12, 2) NOT NULL,
  `refund_policy` ENUM('full', 'partial', 'none') NOT NULL DEFAULT 'none',
  `refund_amount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
  `reason` TEXT NULL,
  `processed_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `checkout_events_reservation_index` (`reservation_id`),
  KEY `checkout_events_property_index` (`property_id`),
  CONSTRAINT `checkout_events_reservation_fk` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `checkout_events_property_fk` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
